### ISSUE TITLE
syscall.Kill not Windows.

### ISSUE THREAD

**Issue by covenant-stars** [rnetx/sing-box#1]
experimental\clashapi\configs.go:84:19: undefined: syscall.Kill
syscall.Kill is for Unix/Linux/Mac systems, not Windows.
This package is locked down. Callers should use the corresponding package in the [golang.org/x/sys 180](http://golang.org/x/sys) repository instead.

**Comment by 0xffffharry** [comment]
Already fixed. Reload does not support windows.
