### ISSUE TITLE
订阅链接支持直连出站

### ISSUE THREAD

**Issue by fwaierr** [rnetx/sing-box#11]
有些订阅链接不能在代理下更新，请支持订阅直连出站

**Comment by 0xffffharry** [comment]
若使用so_mark绕过代理，可以配置proxyprovider中的```request_dialer```配置so_mark绕过代理，使用命令手动更新（也可设置为定时任务）

**Comment by fwaierr** [comment]
> 若使用so_mark绕过代理，可以配置proxyprovider中的`request_dialer`配置so_mark绕过代理，使用命令手动更新（也可设置为定时任务）

好的，谢谢回答
