### ISSUE TITLE
请求下

### ISSUE THREAD

**Issue by woshishiq1** [rnetx/sing-box#12]
用了一段时间了，多个机场，且有需要代理才能下载的订阅。订阅失败后就启动不起来，虽然可以取消订阅间隔时间来防止问题，但对于首次使用还是很不方便，我都是复制粘贴已经不需要代理下载的订阅，然后粘贴改名。使之能进入面板，然后在面板开启代理后在更新代理订阅。问下能不能改成像蓝胖子一样，代理订阅失败也能进面板启动成功

**Comment by 0xffffharry** [comment]
在某个commit后，启动机制已经更改：当获取订阅信息失败后，会弹出warn日志，并使用旧的缓存启动。前提是设置了```cache_file```

**Comment by woshishiq1** [comment]
所以说就是因为首次用内核下载需要代理的订阅下载不下来，才提的这个问题，内核首次用必须要有本地cache_file订阅缓存。虽然我知道怎么解决，但是对于首次使用yaott内核不知道怎么解决需要代理下载的订阅这种问题的人还是不友好，我是从蓝胖子转过来用yaott的，我看蓝胖子内核，下载不到cache_file缓存一样能启动成功。您是开发者我尊重您的想法和决定，只是提一下而已。现在的使用感受已经很不错了

**Comment by 0xffffharry** [comment]
这个问题有人提过，包括我自己也遇到过，不是不能做，是这样做不优雅。某些规则可能会依赖无法正常启动的出站，这样可能会导致启动失败。

**Comment by yaotthaha** [comment]
或者我搞个回落机制，如果启动失败，就将一个可用的出站填充？

**Comment by 0xffffharry** [comment]
我个人认为遇到这个问题主要是~~钱~~机场的问题，订阅机制就是需要高可用，应该让机场解决这个问题而不是让软件去适配因为机场的不稳定因素而带来的问题

**Comment by woshishiq1** [comment]
好的，这确实是不错的解决办法，我用replit搭建订阅转换确实能直连下载订阅，不过怕泄露一直没用这个方法。总之对于懂怎么鼓捣一丢丢的我来说问题不大。感谢开发者的创作
