### ISSUE TITLE
最新next yaott

### ISSUE THREAD

**Issue by woshishiq1** [rnetx/sing-box#14]
![Screenshot_20230911-041006_Trebuchet](https://github.com/yaotthaha/sing-box-pub/assets/90903172/454015cb-379f-453a-8ea8-01d520e9f9e3)
编译报错了什么原因

**Comment by CHIZI-0618** [comment]
https://github.com/yaotthaha/sing-box-pub/blob/a1bb67c53f00bbaea078e505c4c407fcba57d2c5/proxyprovider/proxyprovider.go#L79
  
改成
 ```golang
    var errs []error
```

**Comment by 0xffffharry** [comment]
已修复

**Comment by woshishiq1** [comment]
ok 已经成功编译
