### ISSUE TITLE
[BUG] Proxy-Provider错误转换TUIC中heartbeat-interval字段

### ISSUE THREAD

**Issue by Welt-Drake** [rnetx/sing-box#30]
Meta中将tuic设为 `heartbeat-interval: 10000`

但是转换出来 `"heartbeat": "10μs"`

导致sing-box一直在向服务端发送heartbeat，正常流量无法通行
应转为10s

> Meta wiki
>
> [heartbeat-interval](https://wiki.metacubex.one/config/proxies/tuic/#heartbeat-interval)[¶](https://wiki.metacubex.one/config/proxies/tuic/#heartbeat-interval)
> 
> 可选字段,发送保持连接活动的心跳包的间隔时间,单位为毫秒

**Comment by 0xffffharry** [comment]
已修复 #31
