### ISSUE TITLE
[BUG] sing-box  provider 未处理远端 outbound 与本地 outbound 可能重复的问题

### ISSUE THREAD

**Issue by CHIZI-0618** [rnetx/sing-box#32]
抱歉没有使用 issue 模板
  
注意到最新 commit 支持了原始 sing-box 远端配置的 proxy providers，但我注意到以下问题：

一般来说，远端配置是一个完整的 singbox 配置，当然我们只需要 outbounds 数组，但您可能忘记考虑远端配置可能存在 direct block dns 等本地一般已经存在的出站，singbox 此时会报 出站重复 错误

**Comment by 0xffffharry** [comment]
目前的处理方式是将 block dns urltest seletor 出站排除在外。

sing-box订阅看似方便，但远端发布者的配置文件自由度很高，无法顾及所有可能出现的情况

**Comment by CHIZI-0618** [comment]
> 目前的处理方式是将 block dns urltest seletor 出站排除在外。
> 

direct 出站呢，看到注释在纠结

**Comment by CHIZI-0618** [comment]
~~或许把移除出站类型做成可配置项是更好的解决方案，~~
  
或许可以丰富一下现有的`global_filter`

**Comment by 0xffffharry** [comment]
> ~或许把移除出站类型做成可配置项是更好的解决方案，~
> 
> 或许可以丰富一下现有的`global_filter`

这个之前想过要做，后续会跟上，目前对sing-box配置不知道怎么处理，主要是detour比较头疼
