### ISSUE TITLE
请问您的SFA的proxy-providers的cache路径改怎么填写？

### ISSUE THREAD

**Issue by KyoSakuyo** [rnetx/sing-box#36]
![image](https://github.com/yaotthaha/sing-box-pub/assets/59904064/b35244cf-46fe-4ce9-bb6c-ca4bf713d73a)
我尝试了绝对路径，相对路径，不加路径，都是读取不了，错误提示如图……

**Comment by 0xffffharry** [comment]
请使用绝对路径，或者尝试清除缓存空间

**Comment by KyoSakuyo** [comment]
> 请使用绝对路径，或者尝试清除缓存空间

抱歉我不太清楚安卓端App可以在不主动获取权限的情况下读取设备内的哪些目录？

我将目录设置为/storage/emulated/0/Android/data/io.nekohasekai.sfa/files/providers.json，再尝试了一次，依旧是这个错误提示

**Comment by 0xffffharry** [comment]
请尝试这个目录 ```/sdcard/Android/data/io.nekohasekai.sfa/files``` 或者清除缓存空间

**Comment by KyoSakuyo** [comment]
生效了，但是proxy-providers貌似无法下载并处理托管在git库中的clash.yaml纯文本文件？好奇怪…它会报错missing tags, 生成的cache里只有时间戳。

机场的订阅链接倒是可以正常处理生成缓存文件。
