### ISSUE TITLE
SFA的proxy-providers貌似无法读取文本文件下载格式的订阅链接

### ISSUE THREAD

**Issue by KyoSakuyo** [rnetx/sing-box#37]
![image](https://github.com/yaotthaha/sing-box-pub/assets/59904064/a506cd9d-05d1-4706-a7dd-9a4f5016dae9)
_像是 https://example.com/provider.yaml 这种的_ ，SFA的proxy-providers貌似无法读取文本文件下载格式的订阅链接。如图，文件被处理后的cache在文件管理器中只有时间戳。

_像是https://portal.coffeecloud.top/api/v1/client/subscribe?token=example 这种的_，机场的订阅链接倒是可以正常处理。

**Comment by 0xffffharry** [comment]
1. 请删除 cache 文件后重试
2. 请确保订阅配置文件有可用节点配置

**Comment by 0xffffharry** [comment]
最新源码支持直接使用命令根据链接生成 sing-box 配置

```
# sing-box parselink -l '你的订阅链接'
```

订阅链接支持 clash 订阅，sing-box 订阅，通用订阅。还支持单一节点转换 ```hysteria2://xxxx```

你可以尝试使用命令检查远程配置是否包含节点信息

**Comment by KyoSakuyo** [comment]
同样的文件，一模一样的文件。

机场的订阅链接里的可以正常读取，但是我复制原配置，原封不动地放到github存储库里面后，再读取conf/yaml文件，https://[raw.githubusercontent.com/KyoSakuyo/clash/main/test.conf](https://raw.githubusercontent.com/KyoSakuyo/clash/main/test.conf)——像是这样的。
cache就只能生成时间戳😕
sing-box, clash 格式的都出现了这样的情况。
用的不是最新代码编译的版本，是您在releases里三天前的那个最新发版的SFA。


不知道最新源码编译出的会不会有这样的问题。。

**Comment by 0xffffharry** [comment]
请使用最新源码，因为这几天修了不少问题。

**Comment by KyoSakuyo** [comment]
嘿我不太会安卓编译，就等您在releases里面再发版吧（谢谢你的耐心解答~

**Comment by 0xffffharry** [comment]
刚开 Action 等吧
